// scripts/script.js

const quotes = [
  "The best way to predict the future is to invent it. - Alan Kay",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
  "The purpose of our lives is to be happy. - Dalai Lama",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "Get busy living or get busy dying. - Stephen King",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Act as if what you do makes a difference. It does. - William James",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
  "Never bend your head. Always hold it high. Look the world straight in the eye. - Helen Keller",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
  "When something is important enough, you do it even if the odds are not in your favor. - Elon Musk",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Our lives begin to end the day we become silent about things that matter. - Martin Luther King Jr.",
  "Do not watch the clock. Do what it does. Keep going. - Sam Levenson",
  "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
  "It is always the simple that produces the marvelous. - Amelia Barr",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "The journey of a thousand miles begins with one step. - Lao Tzu",
  "What we achieve inwardly will change outer reality. - Plutarch",
  "Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats",
  "Whether you think you can or you think you can't, you're right. - Henry Ford",
  "The best revenge is massive success. - Frank Sinatra",
  "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "A goal is not always meant to be reached; it often serves simply as something to aim at. - Bruce Lee",
  "Everything you’ve ever wanted is on the other side of fear. - George Addair",
  "In order to succeed, your desire for success should be greater than your fear of failure. - Bill Cosby",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
  "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
  "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
  "You miss 100% of the shots you don’t take. - Wayne Gretzky",
  "It always seems impossible until it's done. - Nelson Mandela",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "The secret of success is to do the common thing uncommonly well. - John D. Rockefeller Jr.",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "The best way to get started is to quit talking and begin doing. - Walt Disney",
  "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
  "Don’t let yesterday take up too much of today. - Will Rogers",
  "You learn more from failure than from success. Don’t let it stop you. Failure builds character. - Unknown",
  "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
  "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you. - Steve Jobs",
  "People who are crazy enough to think they can change the world, are the ones who do. - Rob Siltanen",
  "Failure will never overtake me if my determination to succeed is strong enough. - Og Mandino",
  "We may encounter many defeats but we must not be defeated. - Maya Angelou",
  "Knowing is not enough; we must apply. Wishing is not enough; we must do. - Johann Wolfgang Von Goethe",
  "Imagine your life is perfect in every respect; what would it look like? - Brian Tracy",
  "Security is mostly a superstition. Life is either a daring adventure or nothing. - Helen Keller",
  "The man who has confidence in himself gains the confidence of others. - Hasidic Proverb",
  "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
  "Creativity is intelligence having fun. - Albert Einstein",
  "What you lack in talent can be made up with desire, hustle, and giving 110% all the time. - Don Zimmer",
  "Do what you can with all you have, wherever you are. - Theodore Roosevelt",
  "Develop an ‘attitude of gratitude’. Say thank you to everyone you meet for everything they do for you. - Brian Tracy",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "To see what is right and not do it is a lack of courage. - Confucius",
  "Reading is to the mind, as exercise is to the body. - Brian Tracy",
  "Fake it until you make it! Act as if you had all the confidence you require until it becomes your reality. - Brian Tracy",
  "The future belongs to the competent. Get good, get better, be the best! - Brian Tracy",
  "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded. - Jack Canfield",
  "Things work out best for those who make the best of how things work out. - John Wooden",
  "A room without books is like a body without a soul. - Marcus Tullius Cicero",
  "I think, therefore I am. - René Descartes",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
  "Don’t raise your voice, improve your argument. - Anonymous",
  "The distance between insanity and genius is measured only by success. - Bruce Feirstein",
  "When you stop chasing the wrong things you give the right things a chance to catch you. - Lolly Daskal",
  "I believe that the only courage anybody ever needs is the courage to follow your own dreams. - Oprah Winfrey",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "Whenever you find yourself on the side of the majority, it is time to pause and reflect. - Mark Twain",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "Opportunities don't happen, you create them. - Chris Grosser",
  "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Success is not in what you have, but who you are. - Bo Bennett",
  "You are not a product of your circumstances but a product of your decisions. - Stephen Covey",
  "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
  "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
  "Your positive action combined with positive thinking results in success. - Shiv Khera",
  "Success is not in what you have, but who you are. - Bo Bennett",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
  "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit. - Conrad Hilton",
];

function getRandomQuote() {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  return quotes[randomIndex];
}

function displayQuote() {
  const quoteDisplay = document.getElementById("quoteDisplay");
  const quote = getRandomQuote();
  quoteDisplay.textContent = quote;
}

const newQuote = document.getElementById("newQuote");
newQuote.addEventListener("click", displayQuote);

displayQuote();
